Repository neo-one-suite/neo-one, pull requests merged in 2019-03, with the labels that each got.

#1139 fix(deps): update dependency bignumber.js to v8.1.1
  packages/neo-one-client-common/package.json
  packages/neo-one-client-core/package.json
  packages/neo-one-client-full-core/package.json
  packages/neo-one-developer-tools-frame/package.json
  packages/neo-one-local/package.json
  packages/neo-one-node-consensus/package.json
  packages/neo-one-node-core/package.json
  packages/neo-one-server-plugin-project/package.json
  packages/neo-one-server-plugin-wallet/package.json
  packages/neo-one-smart-contract-compiler/package.json
  packages/neo-one-smart-contract-lib/package.json
  packages/neo-one-smart-contract-test-common/package.json
  packages/neo-one-website/courses/0-tokenomics/0-token/0-contracts/package.json
  packages/neo-one-website/courses/0-tokenomics/0-token/1-properties/package.json
  packages/neo-one-website/courses/0-tokenomics/0-token/2-storage/package.json
  packages/neo-one-website/courses/0-tokenomics/0-token/3-structured-storage/package.json
  packages/neo-one-website/courses/0-tokenomics/0-token/4-constructors/package.json
  packages/neo-one-website/courses/0-tokenomics/0-token/5-methods/package.json
  packages/neo-one-website/courses/0-tokenomics/0-token/6-events/package.json
  packages/neo-one-website/courses/0-tokenomics/0-token/7-transfer/package.json
  packages/neo-one-website/courses/0-tokenomics/1-ico/0-receiving/package.json
  packages/neo-one-website/courses/0-tokenomics/1-ico/1-processing/package.json
  packages/neo-one-website/courses/0-tokenomics/1-ico/2-mint/package.json
  packages/neo-one-website/courses/0-tokenomics/1-ico/3-duration/package.json
  packages/neo-one-website/courses/0-tokenomics/1-ico/4-withdraw/package.json
  packages/neo-one-website/courses/0-tokenomics/2-launch/0-info/package.json
  packages/neo-one-website/courses/0-tokenomics/2-launch/1-balance/package.json
  packages/neo-one-website/courses/0-tokenomics/2-launch/2-participate/package.json
  packages/neo-one-website/courses/0-tokenomics/2-launch/3-reactive/package.json
  packages/neo-one-website/courses/0-tokenomics/2-launch/4-transfer/package.json
  packages/neo-one-website/courses/0-tokenomics/2-launch/5-withdraw/package.json
  packages/neo-one-website/courses/0-tokenomics/3-escrow/0-approvals/package.json
  packages/neo-one-website/courses/0-tokenomics/3-escrow/1-deposit/package.json
  packages/neo-one-website/courses/0-tokenomics/3-escrow/2-transfer/package.json
  packages/neo-one-website/courses/0-tokenomics/3-escrow/3-claim/package.json
  packages/neo-one-website/courses/0-tokenomics/3-escrow/4-refund/package.json
  packages/neo-one-website/courses/0-tokenomics/3-escrow/5-generalize/package.json
  packages/neo-one-website/courses/0-tokenomics/3-escrow/6-cneo/package.json
  packages/neo-one-website/courses/0-tokenomics/3-escrow/7-forward/package.json
  yarn.lock
Labels: conflict cleanup

#1209 fix(jest): remove unnecessary 'async' flags from test
  packages/neo-one-client-core/src/__tests__/sc/BaseFunctionSmartContracts.test.ts
Labels: enhancement

#1208 fix(jest): fix a flaky crypto test - createKeyPair
  packages/neo-one-client-common/src/crypto.ts
  scripts/e2e/One.js
Labels: FINAL REVIEW, enhancement

#1093 feat(node): add node Documentation and Heroku Deployment
  .all-contributorsrc
  app.json
  deploy/Dockerfile
  deploy/static/index.html
  heroku.yml
  packages/neo-one-node-bin/src/utils/getConfiguration.ts
  packages/neo-one-website/docs/4-node/1-docker.md
  packages/neo-one-website/docs/4-node/2-kubernetes.md
  packages/neo-one-website/docs/4-node/3-docker-compose.md
  packages/neo-one-website/docs/4-node/4-build-from-source.md
  packages/neo-one-website/docs/4-node/5-heroku.md
  packages/neo-one-website/docs/4-node/6-configuration.md
  packages/neo-one-website/docs/4-node/config.json
  packages/neo-one-website/docs/5-contributing/0-how-to-contribute.md
  packages/neo-one-website/docs/5-contributing/1-codebase-overview.md
  packages/neo-one-website/docs/5-contributing/2-smart-contract-compiler.md
  packages/neo-one-website/docs/5-contributing/3-code-of-conduct.md
  packages/neo-one-website/docs/5-contributing/config.json
Labels: FINAL REVIEW

#1066 feat(contract-mixins): add DesignatedCaller
  gulpfile.js
  packages/neo-one-smart-contract-lib/src/__data__/contracts/TestDesignatedCaller.ts
  packages/neo-one-smart-contract-lib/src/__tests__/TestDesignatedCallerContract.test.ts
  packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestDesignatedCallerContract.test.ts.snap
  packages/neo-one-smart-contract-lib/src/index.ts
  packages/neo-one-smart-contract-lib/src/ownership/DesignatedCaller.ts
  tsconfig.json
Labels: FINAL REVIEW

#1177 doc(setup): include code-gen config
  packages/neo-one-website/docs/2-advanced-guides/00-native-assets.md
  packages/neo-one-website/docs/2-advanced-guides/01-forward-values.md
  packages/neo-one-website/docs/2-advanced-guides/02-user-accounts.md
  packages/neo-one-website/docs/2-advanced-guides/03-extended-client-apis.md
  packages/neo-one-website/docs/2-advanced-guides/04-raw-client-apis.md
  packages/neo-one-website/docs/2-advanced-guides/05-react.md
  packages/neo-one-website/docs/2-advanced-guides/06-angular.md
  packages/neo-one-website/docs/2-advanced-guides/07-vue.md
  packages/neo-one-website/docs/2-advanced-guides/08-node-deployment.md
  packages/neo-one-website/docs/2-advanced-guides/09-monitor.md
  packages/neo-one-website/docs/2-advanced-guides/10-configuration-options
  packages/neo-one-website/tutorial/tutorial.md
Labels: FINAL REVIEW

#1180 feat(config): add default .onerc config
  packages/neo-one-server-plugin-project/src/initCommand.ts
Labels: FINAL REVIEW

#1057 feat(contract-mixins): add TransferableContract
  packages/neo-one-smart-contract-lib/src/__data__/contracts/TestTransferableContract.ts
  packages/neo-one-smart-contract-lib/src/__tests__/TestTransferableOwnership.test.ts
  packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestTransferableOwnership.test.ts.snap
  packages/neo-one-smart-contract-lib/src/index.ts
  packages/neo-one-smart-contract-lib/src/ownership/TransferableOwnership.ts
Labels: FINAL REVIEW

#1256 refactor(PACK+NEWSTRUCT): Replace PACKSTRUCT with PACK+NEWSTRUCT
  packages/neo-one-client-common/src/models/vm.ts
  packages/neo-one-node-vm/src/__tests__/opcodes.test.ts
  packages/neo-one-node-vm/src/opcodes.ts
  packages/neo-one-server-plugin-project/src/__e2e__/__snapshots__/buildCommand.test.ts.snap
  packages/neo-one-server-plugin-project/src/__e2e__/__snapshots__/buildCommandJs.test.ts.snap
  packages/neo-one-smart-contract-compiler/src/__tests__/compile/helper/contract/__snapshots__/InvokeSmartContractHelper6.test.ts.snap
  packages/neo-one-smart-contract-compiler/src/compile/helper/storage/CreateStructuredStorageHelper.ts
  packages/neo-one-smart-contract-compiler/src/compile/helper/types/WrapHelper.ts
  packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/RedToken.test.ts.snap
  packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestDesignatedCallerContract.test.ts.snap
  packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestICO.test.ts.snap
  packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestToken.test.ts.snap
  packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestTransferableOwnership.test.ts.snap
Labels: FINAL REVIEW

#1212 fix(e2e): reduce expected peer connections to 3
  packages/neo-one-server-plugin-network/src/__e2e__/createNetworkMain.test.ts
Labels: FINAL REVIEW
